# Generated by Django 3.1.4 on 2023-06-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_e_commerce', '0011_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
